# -*- coding: utf-8 -*-
"""AML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qFmrfefZqxDgFFjKPMs9vZYvBQF3rO4o
"""

"""
Dynamic Pricing Optimization Using Deep Q-Learning (DQN)

Цель проекта:
    Обучить агента DQN оптимально управлять ценой товара, учитывая спрос и цены конкурентов.

Состояние (State):
    - current_price: текущая цена товара (0-10)
    - demand: текущий спрос (0-100)
    - competitor_price: цена конкурента (0-10)

Действия (Actions):
    - 0: понизить цену на 1
    - 1: оставить цену без изменений
    - 2: повысить цену на 1

Награда (Reward):
    revenue = current_price * demand - штраф за отклонение от цены конкурента

Зависимости:
    pip install numpy gymnasium stable-baselines3

ВАЖНО: Если запускаете в Google Colab или Jupyter, раскомментируйте строки ниже:
"""

# Раскомментируйте эти строки для установки зависимостей в Colab/Jupyter:
# !pip install -q gymnasium
# !pip install -q stable-baselines3[extra]

import numpy as np
import gymnasium as gym
from gymnasium import spaces
from stable_baselines3 import DQN
from stable_baselines3.common.env_checker import check_env

# Фиксируем seed для воспроизводимости результатов
np.random.seed(42)


class DynamicPricingEnv(gym.Env):
    """
    Кастомная среда для задачи динамического ценообразования.

    Агент управляет ценой товара, стремясь максимизировать выручку,
    при этом учитывая спрос (который зависит от цены) и цены конкурентов.
    """

    metadata = {'render_modes': []}

    def __init__(self):
        super(DynamicPricingEnv, self).__init__()

        # Определяем пространство действий: 3 дискретных действия
        # 0 - понизить цену, 1 - не менять, 2 - повысить цену
        self.action_space = spaces.Discrete(3)

        # Определяем пространство состояний: 3 непрерывных значения
        # [текущая_цена, спрос, цена_конкурента]
        self.observation_space = spaces.Box(
            low=np.array([0.0, 0.0, 0.0], dtype=np.float32),
            high=np.array([10.0, 100.0, 10.0], dtype=np.float32),
            dtype=np.float32
        )

        # Гиперпараметры среды
        self.max_price = 10.0  # максимальная цена
        self.min_price = 1.0   # минимальная цена
        self.price_change = 0.5  # величина изменения цены за один шаг
        self.max_steps = 100   # максимальное количество шагов в эпизоде
        self.alpha = 0.1       # коэффициент штрафа за отклонение от цены конкурента

        # Внутренние переменные
        self.current_price = None
        self.demand = None
        self.competitor_price = None
        self.step_count = None

    def reset(self, seed=None, options=None):
        """
        Сбросить среду в начальное состояние.

        Returns:
            observation: начальное состояние
            info: дополнительная информация (пустой словарь)
        """
        super().reset(seed=seed)

        # Инициализируем начальные значения
        self.current_price = 5.0  # стартовая цена в середине диапазона
        self.competitor_price = 5.0  # конкурент тоже начинает с 5
        self.demand = self._calculate_demand()  # рассчитываем начальный спрос
        self.step_count = 0

        # Формируем начальное наблюдение
        observation = np.array([
            self.current_price,
            self.demand,
            self.competitor_price
        ], dtype=np.float32)

        info = {}

        return observation, info

    def _calculate_demand(self):
        """
        Расчёт спроса на основе текущей цены и цены конкурента.

        Модель спроса:
            - Базовый спрос = 100
            - Спрос уменьшается с ростом нашей цены (коэфф. -10)
            - Спрос увеличивается, если цена конкурента выше (коэфф. +5)
            - Добавляется случайный шум для реалистичности

        Returns:
            demand: спрос (неотрицательное число)
        """
        base_demand = 100
        price_sensitivity = -10  # как сильно цена влияет на спрос
        competitor_effect = 5    # как цена конкурента влияет на наш спрос
        noise = np.random.normal(0, 5)  # случайный шум

        demand = (base_demand +
                  price_sensitivity * self.current_price +
                  competitor_effect * (self.competitor_price - self.current_price) +
                  noise)

        # Спрос не может быть отрицательным
        demand = max(0, demand)

        return demand

    def _update_competitor_price(self):
        """
        Обновить цену конкурента (случайное изменение).

        Конкурент случайным образом меняет цену в пределах [-0.5, +0.5]
        с некоторой вероятностью, иначе оставляет без изменений.
        """
        # С вероятностью 30% конкурент меняет цену
        if np.random.random() < 0.3:
            change = np.random.choice([-0.5, 0.5])
            self.competitor_price += change

            # Ограничиваем цену конкурента разумными пределами
            self.competitor_price = np.clip(
                self.competitor_price,
                self.min_price,
                self.max_price
            )

    def step(self, action):
        """
        Выполнить одно действие в среде.

        Args:
            action: действие агента (0, 1 или 2)

        Returns:
            observation: новое состояние
            reward: полученная награда
            terminated: завершён ли эпизод
            truncated: был ли эпизод прерван по лимиту шагов
            info: дополнительная информация
        """
        # Применяем действие: изменяем цену
        if action == 0:  # понизить цену
            self.current_price -= self.price_change
        elif action == 1:  # оставить цену
            pass
        elif action == 2:  # повысить цену
            self.current_price += self.price_change

        # Ограничиваем цену допустимыми пределами
        self.current_price = np.clip(
            self.current_price,
            self.min_price,
            self.max_price
        )

        # Обновляем цену конкурента
        self._update_competitor_price()

        # Пересчитываем спрос на основе новой цены
        self.demand = self._calculate_demand()

        # Рассчитываем награду
        # Основная компонента: выручка = цена * спрос
        revenue = self.current_price * self.demand

        # Штраф за сильное отклонение от цены конкурента
        # (слишком высокая или низкая цена относительно конкурента - плохо)
        price_diff_penalty = self.alpha * abs(self.current_price - self.competitor_price) * self.demand

        # Итоговая награда
        reward = revenue - price_diff_penalty

        # Увеличиваем счётчик шагов
        self.step_count += 1

        # Проверяем, завершён ли эпизод
        terminated = False  # эпизод не завершается по условиям задачи
        truncated = self.step_count >= self.max_steps  # но ограничен по времени

        # Формируем новое наблюдение
        observation = np.array([
            self.current_price,
            self.demand,
            self.competitor_price
        ], dtype=np.float32)

        # Дополнительная информация для отладки
        info = {
            'revenue': revenue,
            'price_diff_penalty': price_diff_penalty,
            'step': self.step_count
        }

        return observation, reward, terminated, truncated, info


def train_dqn_agent():
    """
    Обучить DQN-агента на задаче динамического ценообразования.
    """
    print("=" * 70)
    print("ОБУЧЕНИЕ DQN-АГЕНТА ДЛЯ ДИНАМИЧЕСКОГО ЦЕНООБРАЗОВАНИЯ")
    print("=" * 70)

    # Создаём среду
    env = DynamicPricingEnv()

    # Проверяем корректность реализации среды (опционально, но полезно)
    print("\n[1] Проверка корректности среды...")
    check_env(env, warn=True)
    print("✓ Среда реализована корректно!\n")

    # Создаём DQN-модель
    print("[2] Создание DQN-модели...")
    model = DQN(
        "MlpPolicy",              # Используем полносвязную нейросеть (MLP)
        env,
        learning_rate=1e-3,       # Скорость обучения
        buffer_size=50000,        # Размер replay buffer
        batch_size=64,            # Размер batch для обучения
        gamma=0.99,               # Коэффициент дисконтирования
        tau=1.0,                  # Коэффициент для soft update target network
        train_freq=1,             # Частота обучения (каждый шаг)
        target_update_interval=1000,  # Частота обновления target network
        exploration_fraction=0.3, # Доля времени на исследование (epsilon decay)
        exploration_initial_eps=1.0,  # Начальный epsilon
        exploration_final_eps=0.05,   # Конечный epsilon
        verbose=1                 # Выводить информацию о процессе обучения
    )
    print("✓ Модель создана!\n")

    # Обучаем модель
    print("[3] Начинаем обучение (50000 шагов)...")
    print("-" * 70)
    model.learn(total_timesteps=50000)
    print("-" * 70)
    print("✓ Обучение завершено!\n")

    # Сохраняем обученную модель
    model_path = "dynamic_pricing_dqn_model"
    model.save(model_path)
    print(f"[4] Модель сохранена в '{model_path}'\n")

    return model_path


def test_trained_agent(model_path, num_episodes=3):
    """
    Протестировать обученного агента.

    Args:
        model_path: путь к сохранённой модели
        num_episodes: количество тестовых эпизодов
    """
    print("=" * 70)
    print("ТЕСТИРОВАНИЕ ОБУЧЕННОГО АГЕНТА")
    print("=" * 70)

    # Создаём среду
    env = DynamicPricingEnv()

    # Загружаем обученную модель
    print(f"\n[1] Загрузка модели из '{model_path}'...")
    model = DQN.load(model_path, env=env)
    print("✓ Модель загружена!\n")

    # Запускаем тестовые эпизоды
    for episode in range(num_episodes):
        print(f"\n{'=' * 70}")
        print(f"ЭПИЗОД {episode + 1}/{num_episodes}")
        print(f"{'=' * 70}")

        obs, info = env.reset()
        episode_reward = 0
        episode_revenue = 0
        done = False
        step = 0

        while not done:
            # Получаем действие от обученной модели (детерминированно)
            action, _states = model.predict(obs, deterministic=True)

            # Преобразуем action в скаляр (если это numpy array)
            action = int(action)

            # Выполняем действие в среде
            obs, reward, terminated, truncated, info = env.step(action)
            done = terminated or truncated

            episode_reward += reward
            episode_revenue += info['revenue']
            step += 1

            # Выводим информацию каждые 20 шагов
            if step % 20 == 0 or done:
                action_names = {0: "ПОНИЗИТЬ", 1: "СОХРАНИТЬ", 2: "ПОВЫСИТЬ"}
                print(f"\nШаг {step}:")
                print(f"  Действие: {action_names[action]} цену")
                print(f"  Текущая цена: {obs[0]:.2f}")
                print(f"  Спрос: {obs[1]:.2f}")
                print(f"  Цена конкурента: {obs[2]:.2f}")
                print(f"  Награда: {reward:.2f}")
                print(f"  Выручка: {info['revenue']:.2f}")

        print(f"\n{'-' * 70}")
        print(f"ИТОГО ЗА ЭПИЗОД {episode + 1}:")
        print(f"  Суммарная награда: {episode_reward:.2f}")
        print(f"  Суммарная выручка: {episode_revenue:.2f}")
        print(f"  Средняя награда за шаг: {episode_reward/step:.2f}")
        print(f"{'-' * 70}")

    env.close()
    print("\n✓ Тестирование завершено!")


def main():
    """
    Главная функция: обучение и тестирование DQN-агента.
    """
    print("\n" + "=" * 70)
    print(" " * 10 + "DYNAMIC PRICING OPTIMIZATION WITH DQN")
    print("=" * 70 + "\n")

    # Этап 1: Обучение агента
    model_path = train_dqn_agent()

    # Этап 2: Тестирование обученного агента
    test_trained_agent(model_path, num_episodes=3)

    print("\n" + "=" * 70)
    print("ПРОГРАММА ЗАВЕРШЕНА УСПЕШНО!")
    print("=" * 70 + "\n")


if __name__ == "__main__":
    main()